# Generated by Django 2.1.7 on 2019-05-17 15:45

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations


def create_django_superuser(apps, schema_editor):
    get_user_model().objects.create_superuser(
        settings.DJANGO_ADMIN_USERNAME,
        settings.DJANGO_ADMIN_EMAIL,
        settings.DJANGO_ADMIN_PASSWORD,
    )


def reverse_django_superuser(apps, schema_editor):
    get_user_model().objects.get(
        username=settings.DJANGO_ADMIN_USERNAME, is_superuser=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [("comics", "0001_initial")]

    operations = [
        migrations.RunPython(create_django_superuser, reverse_django_superuser)
    ]
