# Generated by Django 4.0.3 on 2022-03-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_alter_comic_issue_number_alter_comic_slab_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='year_released',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='issue_number',
            field=models.IntegerField(unique=True),
        ),
    ]
