# Generated by Django 4.0.3 on 2022-03-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_auto_20220306_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='comic_covers/'),
        ),
    ]
