# Generated by Django 4.0.3 on 2022-03-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0009_remove_comic_own_remove_comic_own_slabbed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='cover',
        ),
    ]
