# Generated by Django 4.0.3 on 2022-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0010_remove_comic_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='copy',
            options={'verbose_name_plural': 'Copies'},
        ),
    ]
