# Generated by Django 4.0.3 on 2022-03-26 21:06

from django.db import migrations


def create_xmen_series(apps, schema_editor):
    Series = apps.get_model("comics", "Series")
    Comic = apps.get_model("comics", "Comic")
    series = Series(title="Uncanny X-Men", slug="xmen")
    series.save()

    for comic in Comic.objects.all():
        comic.series = series
        comic.save()


def delete_xmen_series(apps, schema_editor):
    Series = apps.get_model("comics", "Series")
    Comic = apps.get_model("comics", "Comic")

    for comic in Comic.objects.all():
        comic.series = None
        comic.save()

    Series.objects.filter(title="Uncanny X-Men", slug="xmen").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0012_alter_series_options_comic_series"),
    ]

    operations = [migrations.RunPython(create_xmen_series, delete_xmen_series)]
