# Generated by Django 4.0.3 on 2022-03-26 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0013_auto_20220326_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='series',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='comics.series'),
        ),
    ]
